baseURL = 'https://scbase.cn/'


defaultContentLanguage = "zh"  # 设置默认语言
languageCode = "zh-CN"         # 设定 HTML 语言代码
hasCJKLanguage = true          # 让 Hugo 识别中日韩字符，优化字数统计

title = '超级细胞情报站'
theme = 'pehtheme-hugo'

pageSize = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com


[permalinks]
  posts = "/:sections/:year/:month/:slug"

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = '超级细胞'
	mainSections = 'posts'

	[[params.slides]]
    title = "Moco入坑新手问题汇总"
    image = "/moco-qa.webp"
    description = "超级细胞的新游戏mo.co新手必看指南"
    date = "2025-03-20"
    link = "/posts/moco/2025/03/moco_qa"

	[[params.slides]]
    title = "皇室战争国际服苹果手机安装指南"
    image = "/ios_banner.jpg"
    description = "苹果手机玩家必看"
    date = "2025-03-17"
    link = "/posts/clashroyale/2025/03/how-to-play-global-clash-royale"

	[[params.slides]]
    title = "皇室战争国际服安卓手机安装指南"
    image = "/android_banner.jpg"
    description = "安卓手机玩家必看"
    date = "2025-03-17"
    link = "/posts/clashroyale/2025/03/how_to_install_clashroyale_android"





[menu] # Menu management
	[[menu.main]]
		name = '主页'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = '工具'
		pageRef = '/tools'
		weight = 15
	[[menu.main]]
		name = '资源'
		pageRef = '/resources'
		weight = 20
	[[menu.main]]
		name = '关于'
		pageRef = '/about'
		weight = 25

  

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许 Markdown 文件中的 HTML

